on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-variant: ['BC', 'CS']
        racket-version: ['8.17', '8.16']
    name: Test on ${{ matrix.racket-variant }} Racket
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Racket
        uses: Bogdanp/setup-racket@v0.11
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - name: Install Package and its Dependencies
        run: raco pkg show --all
        run: raco pkg install --auto --batch
        run: raco pkg show --all
      - name: Run Tests
        run: raco test -t .
